package usecase

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"my-fiber-app/domain"
)

type reportCardUsecase struct {
	repo     domain.ReportCardRepository
	userRepo domain.UserRepository
}

func NewReportCardUsecase(repo domain.ReportCardRepository, userRepo domain.UserRepository) domain.ReportCardUsecase {
	return &reportCardUsecase{repo: repo, userRepo: userRepo}
}

// buildMonths returns one entry per calendar month from the start month to the end month, inclusive.
// The day of the month is ignored, and every entry starts with paid = false.
func buildMonths(start, end time.Time) []domain.ReportCardMonth {
	cur := time.Date(start.Year(), start.Month(), 1, 0, 0, 0, 0, time.UTC)
	last := time.Date(end.Year(), end.Month(), 1, 0, 0, 0, 0, time.UTC)

	months := []domain.ReportCardMonth{}
	for !cur.After(last) {
		months = append(months, domain.ReportCardMonth{
			Year:  cur.Year(),
			Month: int(cur.Month()),
			Label: fmt.Sprintf("%d-%s", cur.Year(), cur.Month().String()),
			Paid:  false,
		})
		cur = cur.AddDate(0, 1, 0) // safe because the day is always the 1st
	}
	return months
}

func (u *reportCardUsecase) Create(ctx context.Context, card *domain.ReportCard) error {
	// Validate required client-side fields
	if strings.TrimSpace(card.ApplicationID) == "" {
		return errors.New("applicationId is required")
	}
	if strings.TrimSpace(card.FullName) == "" {
		return errors.New("fullName is required")
	}
	if strings.TrimSpace(card.AccNumber) == "" {
		return errors.New("accNumber is required")
	}
	if strings.TrimSpace(card.NIC) == "" {
		return errors.New("nic is required")
	}
	if strings.TrimSpace(card.AppliedGrade) == "" {
    	return errors.New("appliedGrade is required")
	}
	if strings.TrimSpace(card.CurrentGrade) == "" {
    	return errors.New("currentGrade is required")
	}
	if strings.TrimSpace(card.StartDate) == "" {
		return errors.New("startDate is required")
	}
	if strings.TrimSpace(card.EndDate) == "" {
		return errors.New("endDate is required")
	}
	if card.Amount <= 0 {
		return errors.New("amount must be greater than zero")
	}

	// Parse and validate dates
	start, err := time.Parse("2006-01-02", card.StartDate)
	if err != nil {
		return errors.New("startDate must be a valid ISO date (YYYY-MM-DD)")
	}
	end, err := time.Parse("2006-01-02", card.EndDate)
	if err != nil {
		return errors.New("endDate must be a valid ISO date (YYYY-MM-DD)")
	}
	if !end.After(start) {
		return errors.New("endDate must be after startDate")
	}

	// Build the months list (year + month only, day ignored; start and end months both included).
	// Always generated by the server, so anything the client sends in "months" is overwritten.
	card.Months = buildMonths(start, end)

	// Duration and amount follow the months list so they always match
	card.TotalDuration = len(card.Months)
	card.TotalAmount = float64(card.TotalDuration) * card.Amount

	// Auto-generate unique ref number: REF-rec-1, REF-rec-2, ...
	latestRef, _ := u.repo.GetLatestRefNumber(ctx)
	nextNum := 1
	if latestRef != "" {
		// Parse the trailing number from "REF-rec-N"
		parts := strings.Split(latestRef, "-")
		if len(parts) == 3 {
			if num, err := strconv.Atoi(parts[2]); err == nil {
				nextNum = num + 1
			}
		}
	}
	card.RefNumber = fmt.Sprintf("REF-rec-%d", nextNum)

	// Save PDF in root folder (placeholder path)
	card.PdfUrl = fmt.Sprintf("report_cards/%s.pdf", card.RefNumber)

	card.CreatedAt = time.Now()

	return u.repo.Create(ctx, card)
}

func (u *reportCardUsecase) Search(ctx context.Context, query string) ([]*domain.ReportCardSearchSuggestion, error) {
	if strings.TrimSpace(query) == "" {
		return []*domain.ReportCardSearchSuggestion{}, nil
	}
	return u.repo.Search(ctx, query)
}

func (u *reportCardUsecase) GetByApplicationID(ctx context.Context, applicationID string, page int, limit int) (*domain.PaginatedReportCards, error) {
	if strings.TrimSpace(applicationID) == "" {
		return nil, errors.New("applicationId is required")
	}

	// Enforce allowed page sizes: 5, 10, 15 — default to 5
	switch limit {
	case 10, 15:
		// valid
	default:
		limit = 5
	}

	if page < 1 {
		page = 1
	}

	return u.repo.GetByApplicationID(ctx, applicationID, page, limit)
}
func (u *reportCardUsecase) ListSubmissions(ctx context.Context, grade string, page int, limit int) (*domain.PaginatedReportCards, error) {
	switch limit {
	case 10, 15, 20:
		// valid
	default:
		limit = 10
	}
	if page < 1 {
		page = 1
	}

	year := time.Now().Year()
	return u.repo.ListSubmissions(ctx, grade, year, page, limit)
}

func (u *reportCardUsecase) GetOLCertificate(ctx context.Context, id string) (*domain.DocumentVersion, error) {
	if strings.TrimSpace(id) == "" {
		return nil, errors.New("applicationId is required")
	}
	return u.repo.GetOLCertificate(ctx, id)
}

func (u *reportCardUsecase) AddOLCertificate(ctx context.Context, id string, v domain.DocumentVersion) error {
	return u.repo.AddOLCertificate(ctx, id, v)
}

func validatePeriod(year int, fromMonth int, toMonth int) error {
	if year < 2000 || year > 2100 ||
		fromMonth < 1 || fromMonth > 12 ||
		toMonth < 1 || toMonth > 12 ||
		fromMonth > toMonth {
		return domain.ErrInvalidPeriod
	}
	return nil
}

func (u *reportCardUsecase) ListByMonth(ctx context.Context, year int, fromMonth int, toMonth int, grade string, page int, limit int) (*domain.PaginatedMonthReportCards, error) {
	if err := validatePeriod(year, fromMonth, toMonth); err != nil {
		return nil, err
	}

	switch limit {
	case 10, 15, 20:
		// valid
	default:
		limit = 10
	}
	if page < 1 {
		page = 1
	}

	cards, total, err := u.repo.ListByMonth(ctx, year, fromMonth, toMonth, strings.TrimSpace(grade), page, limit)
	if err != nil {
		return nil, err
	}

	rows := make([]*domain.ReportCardMonthRow, 0, len(cards))
	for _, card := range cards {
		row := &domain.ReportCardMonthRow{
			ReportCard:     *card,
			SelectedMonths: []domain.ReportCardMonth{},
		}
		for _, m := range card.Months {
			if m.Year != year || m.Month < fromMonth || m.Month > toMonth {
				continue
			}
			row.SelectedMonths = append(row.SelectedMonths, m)
			if m.Paid {
				row.PaidCount++
			} else {
				row.UnpaidCount++
			}
		}
		rows = append(rows, row)
	}

	totalPages := int((total + int64(limit) - 1) / int64(limit))
	return &domain.PaginatedMonthReportCards{
		Data:       rows,
		Total:      total,
		Page:       page,
		Limit:      limit,
		TotalPages: totalPages,
	}, nil
}

func (u *reportCardUsecase) PayMonths(ctx context.Context, id string, year int, fromMonth int, toMonth int, userID string) (*domain.PayMonthsResult, error) {
	if err := validatePeriod(year, fromMonth, toMonth); err != nil {
		return nil, err
	}
	if strings.TrimSpace(id) == "" {
		return nil, domain.ErrInvalidReportCardID
	}

	// The token only carries user_id, so look up the name
	user, err := u.userRepo.GetUserByID(ctx, userID)
	if err != nil || user == nil {
		return nil, domain.ErrUserNotFound
	}

	paidAt := time.Now().UTC()
	paid, alreadyPaid, err := u.repo.MarkMonthsPaid(ctx, id, year, fromMonth, toMonth, user.Name, userID, paidAt)
	if err != nil {
		return nil, err
	}

	return &domain.PayMonthsResult{
		Year:             year,
		FromMonth:        fromMonth,
		ToMonth:          toMonth,
		PaidMonths:       paid,
		PaidCount:        len(paid),
		AlreadyPaidCount: alreadyPaid,
		PaidAt:           paidAt,
		PaidBy:           user.Name,
	}, nil
}